---
# tasks file for np
    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install NP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx', 'php-fpm' ]
    
# Nginx Configuration
    - name: S`ets Nginx conf file
      template:
        src: "/home/sa/np/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

# Sets Up PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "/home/sa/np/index.php.j2"
        dest: "/var/www/html/index.php"

    - name: creating the directory
      file: 
        path: /opt/nginx/ansible
        state: directory

    - name: replace documents root
      replace:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        regexp: 'root /var/www/html;'
        replace: 'root /opt/nginx/ansible;'
    - name: Enables new root
      file:
        src: "/var/www/html/index.php"
        dest: "/opt/nginx/ansible/index.php"
        state: link
      notify: Reload Nginx	
    - name: replace documents root
      replace:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        regexp: 'root /var/www/html;'
        replace: 'root /opt/nginx/ansible;'	  
    - name: replace port
      replace:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        regexp: 'listen 80;'
        replace: 'listen {{ http_port }};'	 
      notify: Reload Nginx
