---
- hosts: "all"
  become: true
  tasks:
  - name: "Install mysql via apt"
    ansible.builtin.apt:
      name: "mysql-server"
      state: "latest"
      update_cache: "yes"
  - name: "start up the mysql service"
    shell: "service mysql start"
