---
# tasks file for php
    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install NP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'php-fpm' ]
# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
    - name: replace port
      replace:
        path: "/etc/php/8.1/fpm/pool.d/www.conf"
        regexp: 'listen = /run/php/php8.1-fpm.sock'
        replace: 'listen = {{ http_ip_php }}:{{ http_port_php }}'	
      notify: restart php-fpm	
