- hosts: test1
  become: true
  tasks:
    - name: Add sudoers user2 to sudo group
      user:
        name=user2
        groups=sudo
        append=yes
        state=present
        createhome=yes

    - name: Add sudoers user3 to sudo group
      user:
        name=user3
        groups=sudo
        append=yes
        state=present
        createhome=yes

    - name: creating a directory for user2
      file:
        path: /home/user2/.ssh/
        state: directory

    - name: creating a directory for user3
      file:
        path: /home/user3/.ssh/
        state: directory
    - name: copy ssh user2
      synchronize:
        src: /home/sa/.ssh/id_ed3333.pub 
        dest: /home/user2/.ssh/id_ed3333.pub
    - name: copy ssh user3
      synchronize:
        src: /home/sa/.ssh/id_ed3333.pub 
        dest: /home/user3/.ssh/id_et.pub

    - name: Set up authorized keys for the user2
      authorized_key: user=user2 key="{{item}}"
      with_file:
        - /home/sa/.ssh/id_ed3333.pub

    - name: Set up authorized keys for the user3
      authorized_key: user=user3 key="{{item}}"
      with_file:
        - /home/sa/.ssh/id_et.pub
