---
# tasks file for http
    - name: Install Prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install NP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'nginx' ]

# Nginx Configuration
    - name: S`ets Nginx conf file
      template:
        src: "/home/sa/np/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx

    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

# UFW Configuration
    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: replace port
      replace:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        regexp: 'listen 80;'
        replace: 'listen {{ http_port }};'

    - name: Sets Up PHP Info Page
      template:
        src: "/home/sa/np/index.php.j2"
        dest: "/var/www/html/index.php"

    - name: replace php port
      replace:
        path: "/etc/nginx/sites-available/{{ http_conf }}"
        regexp: 'fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;'
        replace: 'fastcgi_pass {{ http_ip_php }}:{{ http_port_php }};'
